#!/usr/bin/env python3
"""
emit_border_auc.py -- une los lotes de check_border_auc.py y genera la tabla del
apendice. Nada se escribe a mano.

    python emit_border_auc.py --parts a/border_auc.json b/... --out ../tex --json-out <dir>
"""
from __future__ import annotations
import argparse, json, os

ORDER = ["PM real (nominal)", "PM simulated", "ECG real (MIT-BIH)", "ECG simulated",
         "Battery real (NASA)", "NOAA tides", "NSRDB solar (GHI)",
         "UCI digits 8x8", "Spoken digits (FSDD)", "MNIST 28x28"]
DIGITS = {"UCI digits 8x8", "Spoken digits (FSDD)", "MNIST 28x28"}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--parts", nargs="+", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--json-out", required=True)
    a = p.parse_args()
    dom, crit = {}, None
    for f in a.parts:
        j = json.load(open(f))
        crit = crit or j["criterion"]
        if j["criterion"] != crit:
            raise SystemExit("los lotes no comparten el criterio")
        for k, v in j["domains"].items():
            v = dict(v); v.pop("per_concept", None); dom[k] = v
    os.makedirs(a.json_out, exist_ok=True)
    json.dump({"criterion": crit, "domains": dom},
              open(os.path.join(a.json_out, "border_auc_all.json"), "w"), indent=1)
    rows = []
    for k in ORDER:
        if k not in dom:
            continue
        v = dom[k]
        at = {int(n): x for n, x in v["auc_at"].items()}
        g = lambda n: f"{at[n]:.3f}" if n in at else "---"
        rows.append(f"{k} & {'other classes' if k in DIGITS else 'IAAFT surrogates'} & "
                    f"{g(1)} & {g(5)} & {g(25)} & {v['auc_final']:.3f} ({v['n_final']}) & "
                    f"{v['n_settle']} & {'yes' if v['pass'] else 'no'} \\\\")
    tex = "\n".join([
        "\\begin{tabular}{llrrrrrl}", "\\toprule",
        " & & \\multicolumn{4}{c}{AUC with $n$ exemplars} & & \\\\",
        "\\cmidrule(lr){3-6}",
        "domain & not the class & $n=1$ & $n=5$ & $n=25$ & final ($n$) & settles at & "
        "$\\le 25$ \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]) + \
        "\n% settles at: first n from which |AUC(n) - AUC(final)| <= 0.01 and stays." \
        "\n% Criterion fixed with the author before the run. Generated by emit_border_auc.py\n"
    open(os.path.join(a.out, "table_border_auc.tex"), "w").write(tex)
    print(tex)


if __name__ == "__main__":
    main()
