#!/usr/bin/env python3
"""
emit_border_deskew.py -- tablas del brazo MNIST con deskew (post hoc, 2026-09-24)
a partir de check_border_auc_deskew.py. Nada se escribe a mano.

    python emit_border_deskew.py --json ../_work/border/mnist_deskew/border_auc_deskew.json --out ../tex

  table_border_deskew.tex   los dos brazos: AUC a n=1,5,25, final y n_settle
  table_border_horizon.tex  n_settle recalculado cortando la MISMA curva en
                            distintos n finales (mismo criterio, |dAUC|<=0.01)
"""
from __future__ import annotations
import argparse, json, os

HORIZONS = [120, 200, 500, 2000, 5000]


def settle(steps, y, tol=0.01):
    f = y[-1]
    for i in range(len(steps)):
        if all(abs(v - f) <= tol for v in y[i:]):
            return steps[i]
    return None


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--json", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args()
    A = json.load(open(a.json))["arms"]
    names = {"raw": "$\\ell_2$ only (as in Table~\\ref{tab:border-auc})",
             "deskew": "deskew, then $\\ell_2$ (declared quotient)"}
    L = ["\\begin{tabular}{lrrrrr}", "\\toprule",
         " & \\multicolumn{3}{c}{AUC with $n$ exemplars} & & \\\\",
         "\\cmidrule(lr){2-4}",
         "MNIST quotient & $n=1$ & $n=5$ & $n=25$ & final ($n$) & settles at \\\\",
         "\\midrule"]
    for k in ("raw", "deskew"):
        d = A[k]; s, y = d["steps"], d["auc"]
        g = lambda n: f"{y[s.index(n)]:.3f}"
        L.append(f"{names[k]} & {g(1)} & {g(5)} & {g(25)} & "
                 f"{y[-1]:.3f} ({s[-1]}) & {settle(s, y)} \\\\")
    L += ["\\bottomrule", "\\end{tabular}",
          "% Generated by emit_border_deskew.py. Deskew arm run after the raw arm",
          "% failed the criterion; criterion and draws unchanged."]
    open(os.path.join(a.out, "table_border_deskew.tex"), "w").write("\n".join(L) + "\n")

    H = ["\\begin{tabular}{rrrrr}", "\\toprule",
         " & \\multicolumn{2}{c}{$\\ell_2$ only} & \\multicolumn{2}{c}{deskew} \\\\",
         "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
         "curve ends at $n$ & final AUC & settles at & final AUC & settles at \\\\",
         "\\midrule"]
    for h in HORIZONS:
        row = [str(h)]
        for k in ("raw", "deskew"):
            s, y = A[k]["steps"], A[k]["auc"]
            j = s.index(h)
            row += [f"{y[j]:.3f}", str(settle(s[:j + 1], y[:j + 1]))]
        H.append(" & ".join(row) + " \\\\")
    H += ["\\bottomrule", "\\end{tabular}",
          "% Generated by emit_border_deskew.py: the same MNIST curves cut at each n,",
          "% settling point recomputed with the criterion of check_border_auc.py."]
    open(os.path.join(a.out, "table_border_horizon.tex"), "w").write("\n".join(H) + "\n")


if __name__ == "__main__":
    main()
