#!/usr/bin/env python3
"""
emit_nn_cover.py -- une los lotes de check_nn_cover.py, reevalua P1 y P2 sobre
todos los dominios y genera la tabla y la figura del apendice.

    python emit_nn_cover.py --parts a/nn_cover.json b/nn_cover.json ... \
        --one-over-n <dir>/one_over_n.json --out ../tex --json-out <dir>
"""
from __future__ import annotations

import argparse, json, os, sys
import numpy as np
from scipy.stats import spearmanr

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "src"))

ORDER = ["PM real (nominal)", "PM simulated", "ECG real (MIT-BIH)", "ECG simulated",
         "Battery real (NASA)", "NOAA tides", "NSRDB solar (GHI)",
         "UCI digits 8x8", "MNIST 28x28", "Spoken digits (FSDD)"]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--parts", nargs="+", required=True)
    p.add_argument("--one-over-n", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--json-out", required=True)
    a = p.parse_args()

    dom = {}
    pred = None
    for f in a.parts:
        j = json.load(open(f))
        pred = pred or j["prediction"]
        if j["prediction"] != pred:
            raise SystemExit("los lotes no comparten la prediccion")
        dom.update(j["domains"])

    n90 = {k: v["n_cov90"] for k, v in dom.items()}
    ok = [v for v in n90.values() if v]
    P1 = {"n_cov90": n90, "ratio": max(ok) / min(ok) if ok else None}
    P1["holds"] = bool(P1["ratio"] and P1["ratio"] >= 3 and len(ok) == len(dom))
    pairs = [(k, abs(v["slope_med"]), 1 / v["d_hat"]) for k, v in dom.items()
             if v.get("d_hat") and v.get("slope_med") is not None]
    rho, pv = spearmanr([x for _, x, _ in pairs], [y for _, _, y in pairs])
    P2 = {"domains": [k for k, _, _ in pairs], "n": len(pairs),
          "spearman": float(rho), "p": float(pv), "holds": bool(rho >= 0.6)}
    out = {"prediction": pred, "domains": dom, "P1": P1, "P2": P2}
    os.makedirs(a.json_out, exist_ok=True)
    json.dump(out, open(os.path.join(a.json_out, "nn_cover_all.json"), "w"), indent=1)

    rows = []
    for k in ORDER:
        if k not in dom:
            continue
        v = dom[k]
        d = v.get("d_hat")
        rows.append(f"{k} & {('%.2f' % d) if d else '---'} & {v['n_cov90']} & "
                    f"{v['n_cov95']} & ${v['slope_med']:.2f}$ & "
                    f"{('$%.2f$' % (-2 / d)) if d else '---'} & ${v['slope_p95']:.2f}$ \\\\")
    tex = "\n".join([
        "\\begin{tabular}{lrrrrrr}", "\\toprule",
        " & & \\multicolumn{2}{c}{coverage at $\\varepsilon$} & "
        "\\multicolumn{3}{c}{decay of $d_{\\mathrm{nn}}$ with $n$} \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-7}",
        "domain & $\\hat d$ & $90\\%$ at & $95\\%$ at & median, $b$ & $-2/\\hat d$ & p95, $b$ \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]) + \
        "\n% Generated by emit_nn_cover.py. b: slope of log d_nn vs log n, 5 <= n <= min(500, N/4)\n"
    open(os.path.join(a.out, "table_nn_cover.tex"), "w").write(tex)

    # figure: the same draws, two measurements
    import figstyle as fs
    import matplotlib.pyplot as plt
    fs.apply()
    oon = json.load(open(a.one_over_n))["domains"]
    fig, axs = plt.subplots(1, 2, figsize=fs.size(1.0, 2.6))
    for k in ORDER:
        if k in oon:
            v = oon[k]
            ns = np.asarray(v["steps"], float)
            m = np.asarray(v["rel_measured"])
            ok_ = (m > 0) & (ns <= 2000)
            axs[0].plot(ns[ok_], m[ok_], color=fs.BLUE, lw=0.9, alpha=0.75)
        if k in dom:
            v = dom[k]
            ns = np.asarray(v["steps"], float)
            y = np.asarray(v["med"]) / v["med"][0]
            sel = ns <= 2000
            axs[1].plot(ns[sel], y[sel], color=fs.ORANGE, lw=0.9, alpha=0.85)
    # Direct labels on the right panel, at the end of each line. Labels that
    # end at the same n are spread in log10(y) to a minimum gap, so that no two
    # overlap; a thin leader joins a moved label to its line.
    SHORT = {"PM real (nominal)": "PM", "PM simulated": "PM sim.",
             "ECG real (MIT-BIH)": "ECG", "ECG simulated": "ECG sim.",
             "Battery real (NASA)": "battery", "NOAA tides": "tides",
             "NSRDB solar (GHI)": "solar", "UCI digits 8x8": "UCI",
             "MNIST 28x28": "MNIST", "Spoken digits (FSDD)": "spoken"}
    ends = []
    for k in ORDER:
        if k in dom:
            v = dom[k]
            ns = np.asarray(v["steps"], float)
            y = np.asarray(v["med"]) / v["med"][0]
            sel = ns <= 2000
            ends.append([ns[sel][-1], float(np.log10(y[sel][-1])), SHORT[k]])
    GAP = 0.16
    groups = {}
    for e in ends:
        groups.setdefault(round(np.log10(e[0]), 1), []).append(e)
    for g in groups.values():
        g.sort(key=lambda e: e[1])
        pos = [e[1] for e in g]
        for i in range(1, len(pos)):
            pos[i] = max(pos[i], pos[i - 1] + GAP)
        shift = (np.mean([e[1] for e in g]) - np.mean(pos)) if len(g) > 1 else 0.0
        for e, yl in zip(g, pos):
            yl += shift
            axs[1].annotate(e[2], xy=(e[0], 10 ** e[1]), xytext=(e[0] * 1.35, 10 ** yl),
                            fontsize=fs.TICK - 0.5, color=fs.INK, va="center",
                            arrowprops=dict(arrowstyle="-", lw=0.4, color=fs.MUTED,
                                            shrinkA=0, shrinkB=0))
    axs[1].set_xlim(0.8, 2000 * 12)
    x = np.array([1, 2000.0])
    axs[0].plot(x, 1 / x, "--", color=fs.INK, lw=0.8)
    axs[0].text(400, 1 / 400 * 0.35, "$1/n$", color=fs.INK, fontsize=fs.TICK)
    for ax, t in zip(axs, ("distance to the centroid of what was seen\n(relative residual)",
                           "distance to the nearest exemplar seen\n(median, relative to $n=1$)")):
        ax.set_xscale("log"); ax.set_yscale("log")
        fs.style(ax); fs.ident(ax, t)
        ax.set_xlabel("$n$")
    fig.tight_layout()
    fs.save(fig, os.path.join(a.out, "fig_nn_cover.png"))
    plt.close(fig)
    print(json.dumps({"P1": P1, "P2": P2}, indent=1))


if __name__ == "__main__":
    main()
