#!/usr/bin/env python3
"""
emit_maximum_appendix.py -- tablas y figura del apendice "What the sample maximum
measures", generadas desde los JSON de check_one_over_n.py y
check_boundary_quantile.py. Nada se escribe a mano.

    python emit_maximum_appendix.py --one-over-n <dir> --quantile <dir> --out ../tex
"""
from __future__ import annotations

import argparse, json, os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "src"))

ORDER = ["PM real (nominal)", "PM simulated", "ECG real (MIT-BIH)", "ECG simulated",
         "Battery real (NASA)", "NOAA tides", "NSRDB solar (GHI)",
         "UCI digits 8x8", "MNIST 28x28", "Spoken digits (FSDD)"]


def tab(colspec, head, rows):
    return "\n".join(["\\begin{tabular}{" + colspec + "}", "\\toprule", *head,
                      "\\midrule", *rows, "\\bottomrule", "\\end{tabular}"]) + "\n"


def one_over_n(path):
    d = json.load(open(path))["domains"]
    head = [" & & \\multicolumn{2}{c}{$n=5$} & \\multicolumn{2}{c}{$n=20$} & "
            "\\multicolumn{2}{c}{$n=50$} & \\\\",
            "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
            "domain & $|\\bar c|$ & meas. & pred. & meas. & pred. & meas. & pred. & "
            "meas./pred. \\\\"]
    rows = []
    for k in ORDER:
        if k not in d:
            continue
        v = d[k]
        cells = []
        for n in ("5", "20", "50"):
            a = v["at"].get(n)
            cells += (["---", "---"] if a is None else
                      [f"{100*a['measured']:.1f}", f"{100*a['C']:.1f}"])
        rows.append(f"{k} & {v['c_norm']:.3f} & " + " & ".join(cells) +
                    f" & {v['median_ratio_measured_over']['C']:.2f} \\\\")
    return tab("lrrrrrrrr", head, rows) + \
        "% residual in per cent; pred. = tr(S_perp)/(2n|c|(1-|c|)) (N+n)/(N-1)\n" \
        "% meas./pred. = median ratio over 2 <= n <= N/4. Generated by emit_maximum_appendix.py\n"


def concentration(path):
    d = json.load(open(path))["domains"]
    head = [" & & \\multicolumn{3}{c}{growth over the last doubling of $n$} & "
            "\\multicolumn{2}{c}{maximum pairs, $n\\ge1280$} \\\\",
            "\\cmidrule(lr){3-5}\\cmidrule(lr){6-7}",
            "domain & pool & p99 & p99.9 & maximum & top five in & distinct \\\\"]
    rows = []
    for k in ORDER:
        if k not in d or "top5_share" not in d[k]:
            continue
        v = d[k]
        t = v["tail_last_doubling"]
        rows.append(f"{k} & {v['N']} & {100*t['p99']:+.1f}\\% & {100*t['p999']:+.1f}\\% & "
                    f"{100*t['max']:+.1f}\\% & {100*v['top5_share']:.0f}\\% of "
                    f"{v['n_max_pairs']} & {v['distinct_in_max_pairs']} \\\\")
    return tab("lrrrrrr", head, rows) + \
        "% Generated by emit_maximum_appendix.py from boundary_quantile.json\n"


def figure(offenders, out):
    import figstyle as fs
    import matplotlib.pyplot as plt
    o = json.load(open(offenders))
    fs.apply()
    fig, axs = plt.subplots(1, 2, figsize=fs.size(1.0, 2.3))
    # Which of the five most frequent realisations is which was read from the
    # curves and checked mechanically: a cut beat has the preceding R wave in
    # the first eight samples and a run of 78 identical zeros; a constant
    # trace is one value over all 160 samples.
    spec = [("ECG real (MIT-BIH)", "Measured ECG", {
                "8255": "cut beat", "3857": "cut beat", "704": "cut beat",
                "9775": "wide complex", "853": "wide complex"}),
            ("Battery real (NASA)", "Battery discharge", {
                "1811": "constant trace", "2090": "constant trace",
                "2711": "interpolated gap"})]
    colour = {"cut beat": fs.VERMILLION, "wide complex": fs.BLUE,
              "constant trace": fs.ORANGE, "interpolated gap": fs.VERMILLION}
    for ax, (key, title, pick) in zip(axs, spec):
        e = o[key]
        ax.plot(e["typical"], color=fs.GHOST, lw=2.2, label="typical")
        seen = set()
        for i, lab in pick.items():
            c = colour[lab]
            y = e["top"].get(i)
            if y is None:
                continue
            ax.plot(y, color=c, lw=1.0, label=lab if lab not in seen else None)
            seen.add(lab)
        fs.style(ax)
        fs.ident(ax, title)
        ax.set_xlabel("sample")
        ax.legend(frameon=False, fontsize=fs.LEGEND - 1)
    fig.tight_layout()
    fs.save(fig, out)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--one-over-n", required=True)
    p.add_argument("--quantile", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args()
    open(os.path.join(a.out, "table_one_over_n.tex"), "w").write(
        one_over_n(os.path.join(a.one_over_n, "one_over_n.json")))
    open(os.path.join(a.out, "table_max_concentration.tex"), "w").write(
        concentration(os.path.join(a.quantile, "boundary_quantile.json")))
    figure(os.path.join(a.quantile, "offenders.json"),
           os.path.join(a.out, "fig_max_offenders.png"))
    print("ok")


if __name__ == "__main__":
    main()
